
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package br.ufmg.dcc.fernandes.ivan.parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int GTEQ = 25;
  public static final int MULT = 31;
  public static final int CHAR = 3;
  public static final int LTEQ = 24;
  public static final int LPAREN = 16;
  public static final int INT = 2;
  public static final int MINUS = 30;
  public static final int RPAREN = 17;
  public static final int OROR = 28;
  public static final int BOOLEAN_LITERAL = 11;
  public static final int NOT = 22;
  public static final int SEMICOLON = 18;
  public static final int LT = 21;
  public static final int DIV = 32;
  public static final int ANDAND = 27;
  public static final int PLUS = 29;
  public static final int IF = 6;
  public static final int EOF = 0;
  public static final int BOOLEAN = 5;
  public static final int error = 1;
  public static final int EQEQ = 23;
  public static final int BREAK = 10;
  public static final int EQ = 19;
  public static final int LBRACK = 14;
  public static final int FLOATING_POINT_LITERAL = 35;
  public static final int LBRACE = 12;
  public static final int ELSE = 7;
  public static final int RBRACK = 15;
  public static final int WHILE = 9;
  public static final int FLOAT = 4;
  public static final int RBRACE = 13;
  public static final int GT = 20;
  public static final int DO = 8;
  public static final int NOTEQ = 26;
  public static final int INTEGER_LITERAL = 34;
  public static final int IDENTIFIER = 33;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INT",
  "CHAR",
  "FLOAT",
  "BOOLEAN",
  "IF",
  "ELSE",
  "DO",
  "WHILE",
  "BREAK",
  "BOOLEAN_LITERAL",
  "LBRACE",
  "RBRACE",
  "LBRACK",
  "RBRACK",
  "LPAREN",
  "RPAREN",
  "SEMICOLON",
  "EQ",
  "GT",
  "LT",
  "NOT",
  "EQEQ",
  "LTEQ",
  "GTEQ",
  "NOTEQ",
  "ANDAND",
  "OROR",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "IDENTIFIER",
  "INTEGER_LITERAL",
  "FLOATING_POINT_LITERAL"
  };
}

